name: Auto PR develop → main

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  pull-requests: write

jobs:
  sync-develop-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop

      - name: Fetch main for comparison
        run: git fetch origin main

      - name: Check if there are changes between develop and main
        id: diff
        run: |
          if git diff --quiet origin/main HEAD; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create or update PR develop → main
        if: steps.diff.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main               # <- PR target
          branch: auto/develop-to-main # <- PR source branch (bot branch, not develop itself)
          title: "Auto-merge develop → main"
          body: "This PR was auto-created to merge the latest `develop` into `main`"
          commit-message: "chore: sync develop → main"
          labels: automated
          auto-merge: true
          merge-method: merge
