name: Auto-merge develop into main

on:
  push:
    branches:
      - develop

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Wait 15 minutes
        run: sleep 900 # 900 seconds = 15 minutes

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge develop into main
        run: |
          git fetch origin
          git checkout main
          git merge origin/develop --no-edit
          git push origin main
